{{- if .Values.cloudflared.sealedSecretCert }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: {{ include "argo-tunnel.fullname" . }}
spec:
  encryptedData:
    "cert.pem": {{ .Values.cloudflared.sealedSecretCert }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: {{ include "argo-tunnel.fullname" . }}
{{- end }}
