repositories:
- name: external-secrets
  url: https://external-secrets.github.io/kubernetes-external-secrets/
helmDefaults:
  atomic: true
  cleanupOnFail: true
  createNamespace: true
releases:
- name: external-secrets
  namespace: external-secrets
  chart: external-secrets/kubernetes-external-secrets
  version: 8.2.2
  labels:
    app: external-secrets
  missingFileHandler: Error
  values:
  - values.yaml
