## Discovery Settings
pilot:
  autoscaleEnabled: false
  replicaCount: 1

  # Resources for a small pilot install
  resources:
    requests:
      cpu: 500m
      memory: 2048Mi

global:
  # Used to locate istiod.
  istioNamespace: istio-system
  # enable pod disruption budget for the control plane, which is used to
  # ensure Istio control plane components are gradually upgraded or recovered.
  defaultPodDisruptionBudget:
    enabled: false
    # The values aren't mutable due to a current PodDisruptionBudget limitation
    # minAvailable: 1

