# releases:
# - name: sealed-secret-key
#   namespace: kube-system
#   chart: raw/raw
#   version: 1.1.0
#   labels:
#     app: sealed-secret-key
#   missingFileHandler: Error
#   values:
#   - resources:
#     - {{ readFile "/home/chris/keys/sealed-secrets.key" | nindent 6 }}
# # name and namespace as expected by kubeseal natively
# - name: sealed-secrets-controller
#   namespace: kube-system
#   chart: sealed-secrets/sealed-secrets
#   version: 1.16.1
#   labels:
#     app: sealed-secrets
#   missingFileHandler: Error
#   values:
#     - ../sealed-secrets/values.yaml
